spring.application.name=PortalContabil

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (Dinâmico para Render/Local)
# ==========================================
# Se houver a variável DB_URL (na Render), usa ela. Se não, usa o localhost.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portal_contabil}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate trate UUIDs corretamente no Postgres
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

# ==========================================
# SEGURANÇA E JWT
# ==========================================
# Chave secreta para assinar o token.
api.security.token.secret=${JWT_SECRET:Y29udGFodWItc2VjcmV0LWtleS1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OQ==}

# ==========================================
# UPLOAD DE ARQUIVOS (Requisito RNF07)
# ==========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================================
# CONFIGURAÇÕES DO SERVIDOR
# ==========================================
# A Render exige ler a porta dinamicamente através da variável ${PORT}
server.port=${PORT:8080}
server.error.include-message=always

# ==========================================
# CONFIGURAÇÕES DO JAVA MAIL SENDER (Gmail)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mc4220762@gmail.com
# Mantido seguro por enquanto, mas o ideal é mover para variável em produção
spring.mail.password=eicoabeygmbephtz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.banner-mode=off