spring.application.name=PortalContabil

# ==========================================
# CONFIGURACAO DO BANCO DE DADOS (Dinamico para Render/Local)
# ==========================================
# Se houver a variavel DB_URL (na Render), usa ela. Se nao, usa o localhost.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portal_contabil}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate trate UUIDs corretamente no Postgres
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

# ==========================================
# SEGURANCA E JWT
# ==========================================
# Chave secreta para assinar o token.
api.security.token.secret=${JWT_SECRET:Y29udGFodWItc2VjcmV0LWtleS1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OQ==}

# ==========================================
# UPLOAD DE ARQUIVOS (Requisito RNF07)
# ==========================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================================
# CONFIGURACOES DO SERVIDOR
# ==========================================
# A Render exige ler a porta dinamicamente atraves da variavel ${PORT}
server.port=${PORT:8080}
server.error.include-message=always

#===========================================
# CONFIGURACOES DO JAVA MAIL SENDER (Hostinger Oficial)
# ==========================================
spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=gestao@portalcontabil.site
spring.mail.password=C@ntabil77

# Propriedades cruciais para rodar na Render sem bloqueio (SSL Direto)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

spring.main.banner-mode=off