spring.application.name=PortalContabil
# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (PostgreSQL)
# ==========================================
spring.datasource.url = jdbc:postgresql://localhost:5432/portal_contabil
spring.datasource.username = postgres
spring.datasource.password = root

# Drive do PostgreSQL
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# 'update' cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate trate UUIDs corretamente no Postgres
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

# ==========================================
# SEGURANÇA E JWT
# ==========================================
# Chave secreta para assinar o token. Em produção, use uma variável de ambiente.
api.security.token.secret=${JWT_SECRET:Y29udGFodWItc2VjcmV0LWtleS1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OQ==}

# ==========================================
# UPLOAD DE ARQUIVOS (Requisito RNF07)
# ==========================================
# Define o tamanho máximo dos documentos (ex: notas fiscais, extratos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================================
# CONFIGURAÇÕES DO SERVIDOR
# ==========================================
server.port=8080
server.error.include-message=always

# Desativa o banner do Spring na inicialização (opcional)
spring.main.banner-mode=off




